[package]
name = "patternscript"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "patternscript"

[dependencies]
anyhow = "1.0.56"
thiserror = "1.0.30"
cgmath = "0.18.0"
# ouroboros = "0.15.0"
itertools = "0.10.3"