[package]
name = "patternscript_visual"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
patternscript = {path = "../patternscript"}
cgmath = "0.18.0"